title: MOLGENIS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  MOLGENIS open source project website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
layout: green #default layout

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-cayman